services:
  database:
    image: mysql:8.4
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql84data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - docker_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    depends_on:
      - database
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"
    networks:
      - docker_network

networks:
  docker_network:
    external: true

volumes:
  mysql84data: