services:
  redis:
    image: redis:alpine3.21
    container_name: database-redis-alpine-3-21
    restart: always
    networks:
      - unand_network
    ports:
      - "6379:6379"

networks:
  unand_network:
    external: true

