services:
  database:
    image: mysql:5.7
    container_name: database-mysql57
    restart: unless-stopped
    volumes:
      - data-mysql57:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3307:3306"
    networks:
      - unand_network

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin-mysql57
    restart: unless-stopped
    environment:
      - PMA_HOST=database
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "8082:80"
    depends_on:
      - database
    networks:
      - unand_network

networks:
  unand_network:
    external: true

volumes:
  data-mysql57:
