services:
  database:
    image: mysql:9.2
    container_name: database-mysql92
    volumes:
      - data-mysql92:/var/lib/mysql
      # - ./my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=toor12345
    ports:
      - "3309:3306"
    networks:
      - unand_network

networks:
  unand_network:
    external: true

volumes:
  data-mysql92:
