
services:
  app:
    image: php-nginx-base
    ports:
      - "8000:80"
    volumes:
      - ./src:/var/www/html
      - ./docker-config/php.ini:/usr/local/etc/php/conf.d/99-custom.ini
      - ./docker-config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker-config/supervisord.conf:/etc/supervisord.conf
      - ./docker-config/entrypoint.sh:/entrypoint.sh
    # environment:
      # - DB_HOST=host.docker.internal
      # - DB_PORT=3306
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # frontend:
  #   image: php-nginx-base
  #   ports:
  #     - "8001:80"
  #   volumes:
  #     - ./src-frontend:/var/www/html
  #     - ./docker-config/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ./docker-config/supervisord.conf:/etc/supervisord.conf
  #     - ./docker-config/entrypoint.sh:/entrypoint.sh
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"