services:
  database:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: simpeg
      MYSQL_USER: simpeg
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql80data:/var/lib/mysql
    networks:
      - docker_network
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --max_connections=200

  phpmyadmin:
    image: phpmyadmin:5.2
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      UPLOAD_LIMIT: 128M
    ports:
      - "8081:80"
    networks:
      - docker_network

networks:
  docker_network:
    external: true

volumes:
  mysql80data:
